apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-auth-server-deployment
  labels:
    app: jwt-auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jwt-auth-app
  template:
    metadata:
      labels:
        app: jwt-auth-app
    spec:
      containers:
        - name: jwt-auth-continer
          image: shivapatel1102001/jwt-auth-image:v1
          ports:
            - containerPort: 80
